<a href="https://colab.research.google.com/github/Austin-Capp/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [5]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Education',
    'Age',
    'DistanceFromHome',
    'JobSatisfaction',
    'OverTime',
    'StockOptionLevel',
    'WorkLifeBalance',
    'YearsAtCompany',
    'YearsSinceLastPromotion',
    'NumCompaniesWorked'
]

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [ ]:
# Create a list of at least 10 column names to use as X data


# Create X_df using your selected columns


# Show the data types for X_df


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split


In [9]:
# Covert your X data to numeric data types however you see fit
# Add new code cells as necessary

# Calculate the count of unique values in the 'OverTime' column
X_df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary


OverTime
No     797
Yes    305
Name: count, dtype: int64

In [16]:
# Import dependencies (if not already imported)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Step 1: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

# Step 2: Convert non-numeric columns to numeric values
# Convert 'OverTime' column to numeric
X_train['OverTime'] = X_train['OverTime'].map({'Yes': 1, 'No': 0})
X_test['OverTime'] = X_test['OverTime'].map({'Yes': 1, 'No': 0})

# Verify that all columns are now numeric
print("X_train dtypes after conversion:\n", X_train.dtypes)

# Step 3: Create and fit the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data
scaler.fit(X_train)

# Step 4: Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train dtypes after conversion:
 Education                  int64
Age                        int64
DistanceFromHome           int64
JobSatisfaction            int64
OverTime                   int64
StockOptionLevel           int64
WorkLifeBalance            int64
YearsAtCompany             int64
YearsSinceLastPromotion    int64
NumCompaniesWorked         int64
dtype: object


In [17]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Create a StandardScaler


# Fit the StandardScaler to the training data


# Scale the training and testing data


In [22]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Step 1: Inspect the column names in attrition_df
print("Column names in attrition_df:\n", attrition_df.columns)

# Step 2: Adjust column names (if needed)
# Strip whitespace and check actual column names
attrition_df.columns = attrition_df.columns.str.strip()

# Ensure y_df is created with the correct column names
y_df = attrition_df[['Attrition', 'Department']]  # Adjust for actual column names if necessary

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

# Step 4: Create a OneHotEncoder for the department column
dept_encoder = OneHotEncoder(sparse_output=False)

# Step 5: Fit the encoder to the 'Department' column in the training data
dept_encoder.fit(y_train[['Department']])

# Step 6: Transform the 'Department' column in training and testing data
X_train_dept = dept_encoder.transform(y_train[['Department']])
X_test_dept = dept_encoder.transform(y_test[['Department']])

# Step 7: Verify the encoded result
print("Encoded training data for 'Department':\n", X_train_dept)
print("Shape of the encoded data:", X_train_dept.shape)


Column names in attrition_df:
 Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')
Encoded training data for 'Department':
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of the encoded data: (1176, 3)


In [ ]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
dept_encoder.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
from sklearn.preprocessing import OneHotEncoder

# Step 1: Create a OneHotEncoder for the attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Step 2: Fit the encoder to the 'Attrition' column in the training data
attrition_encoder.fit(y_train[['Attrition']])

# Step 3: Transform the 'Attrition' column in training and testing data
X_train_attrition = attrition_encoder.transform(y_train[['Attrition']])
X_test_attrition = attrition_encoder.transform(y_test[['Attrition']])

# Step 4: Verify the encoded result
print("Encoded training data for 'Attrition':\n", X_train_attrition)
print("Shape of the encoded data:", X_train_attrition.shape)


Encoded training data for 'Attrition':
 [[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
Shape of the encoded data: (1176, 2)


In [ ]:
# Create a OneHotEncoder for the Attrition column


# Fit the encoder to the training data


# Create two new variables by applying the encoder
# to the training and testing data


array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [28]:
# Find the number of columns in the X training data
input_dim = X_train_scaled.shape[1]
print("Number of input features:", input_dim)

from tensorflow.keras import layers

# Create the input layer
input_layer = layers.Input(shape=(input_dim,))

# Create shared layers
shared_layer_1 = layers.Dense(units=128, activation='relu')(input_layer)
shared_layer_2 = layers.Dense(units=64, activation='relu')(shared_layer_1)


Number of input features: 10


In [ ]:
# Find the number of columns in the X training data.


# Create the input layer


# Create at least two shared layers


In [29]:
# Create the hidden layer for the Department branch
dept_hidden_layer = layers.Dense(units=32, activation='relu')(shared_layer_2)

# Create the output layer for the Department branch
dept_output_layer = layers.Dense(units=3, activation='softmax', name='department_output')(dept_hidden_layer)


In [ ]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer


In [30]:
# Create the hidden layer for the Attrition branch
attrition_hidden_layer = layers.Dense(units=16, activation='relu')(shared_layer_2)

# Create the output layer for the Attrition branch
attrition_output_layer = layers.Dense(units=2, activation='softmax', name='attrition_output')(attrition_hidden_layer)


In [ ]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer


# Create the output layer


In [31]:
from tensorflow.keras import Model

# Create the model
model = Model(
    inputs=input_layer,
    outputs=[dept_output_layer, attrition_output_layer],
    name="Multi_Output_Model"
)

# Compile the model
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy'
    },
    metrics={
        'department_output': ['accuracy'],
        'attrition_output': ['accuracy']
    }
)

# Summarize the model
model.summary()


Model: "Multi_Output_Model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 128)            │          1,408 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 64)             │          8,256 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 32)             │          2,080 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 16)             │          1,040 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             34 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 12,917 (50.46 KB)

 Trainable params: 12,917 (50.46 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Create the model


# Compile the model


# Summarize the model


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)        │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared1 (Dense)           │ (None, 64)             │            704 │ input[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared2 (Dense)           │ (None, 128)            │          8,320 │ shared1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 32)             │          4,128 │ shared2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             66 │ attrition_hidden[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ department_hidden[0][… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
# Train the model
history = model.fit(
    X_train_scaled,  # Input data
    {'department_output': X_train_dept, 'attrition_output': X_train_attrition},  # Targets for both outputs
    validation_split=0.2,  # Reserve 20% of the training data for validation
    epochs=20,  # Number of training epochs
    batch_size=32,  # Number of samples per batch
    verbose=1  # Print training progress
)


Epoch 1/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - attrition_output_accuracy: 0.5552 - attrition_output_loss: 0.6723 - department_output_accuracy: 0.3925 - department_output_loss: 1.0774 - loss: 1.7499 - val_attrition_output_accuracy: 0.7966 - val_attrition_output_loss: 0.5230 - val_department_output_accuracy: 0.6314 - val_department_output_loss: 0.8681 - val_loss: 1.4157
Epoch 2/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8375 - attrition_output_loss: 0.4465 - department_output_accuracy: 0.6539 - department_output_loss: 0.8181 - loss: 1.2639 - val_attrition_output_accuracy: 0.7966 - val_attrition_output_loss: 0.4824 - val_department_output_accuracy: 0.6314 - val_department_output_loss: 0.8036 - val_loss: 1.3140
Epoch 3/20
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8357 - attrition_output_loss: 0.4100 - department_output_accuracy: 0.6512 - department_output_loss: 0.7961 - loss: 1.2057 - val_attrition_output_accuracy: 0.7966 - va

In [ ]:
# Train the model


Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - attrition_output_accuracy: 0.6931 - department_output_accuracy: 0.5956 - loss: 1.4833
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8335 - department_output_accuracy: 0.6383 - loss: 1.2524
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - attrition_output_accuracy: 0.8421 - department_output_accuracy: 0.6393 - loss: 1.1859
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8389 - department_output_accuracy: 0.6692 - loss: 1.1473
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8714 - department_output_accuracy: 0.6484 - loss: 1.0626
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8700 - department_output_accuracy: 0.6445 - loss: 1.0750
Epoch 7/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8708 - department_output_accuracy: 0.6443 - loss: 1.0567
Epoch 8/100
35/35 ━━━━━━━━

In [33]:
# Evaluate the model with the testing data
evaluation_results = model.evaluate(
    X_test_scaled,  # Input test data
    {'department_output': X_test_dept, 'attrition_output': X_test_attrition},  # Test targets for both outputs
    verbose=1  # Print progress
)

# Print the evaluation results
print("Evaluation Results:", evaluation_results)


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8643 - attrition_output_loss: 0.4025 - department_output_accuracy: 0.6319 - department_output_loss: 0.8955 - loss: 1.3018 
Evaluation Results: [1.2788516283035278, 0.8532659411430359, 0.4046332836151123, 0.8571428656578064, 0.6530612111091614]


In [ ]:
# Evaluate the model with the testing data


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.7868 - department_output_accuracy: 0.4877 - loss: 4.0711  


[4.038690090179443, 0.7880434989929199, 0.5]

In [34]:
# Extract accuracy values for department and attrition from the evaluation results
department_accuracy = evaluation_results[3]
attrition_accuracy = evaluation_results[4]

# Print the accuracy for both branches
print(f"Department Accuracy: {department_accuracy * 100:.2f}%")
print(f"Attrition Accuracy: {attrition_accuracy * 100:.2f}%")


Department Accuracy: 85.71%
Attrition Accuracy: 65.31%


In [ ]:
# Print the accuracy for both department and attrition


Attrition predictions accuracy: 0.7880434989929199
Department predictions accuracy: 0.5


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy is less effective for imbalanced data. Metrics like F1-score or AUC-ROC are better for deeper insights when class distribution or misclassification costs matter.

2. I chose softmax for both output layers because it provides probabilities, ideal for multi-class (Department) and binary (Attrition) classifications.

3. Here are a few ways to enhance the model:

1. **Feature Engineering**: Add or refine features, such as interaction terms or embeddings, to better capture complex relationships in the data.
2. **Regularization**: Use techniques like dropout or L2 regularization to prevent overfitting and improve generalization.
3. **Hyperparameter Tuning**: Optimize parameters like layer size, number of neurons, learning rate, and batch size using tools like GridSearch or Bayesian optimization.
4. **Alternative Architectures**: Experiment with advanced architectures such as recurrent or attention-based layers for capturing temporal or contextual relationships.
5. **Data Augmentation**: If the dataset is small, consider synthetic data generation or augmentation to improve model performance and robustness.